name = "SimpleWebsockets"
uuid = "129f17fe-97ed-471b-8d4c-fbfa5a103ea8"
authors = ["Michael Jonker <michael@openpoint.ie> and contributors"]
version = "0.1.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
HTTP = "0.8"
MbedTLS = "0.6.8, 0.7, 1"
Suppressor = "0.2"
julia = "1"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor"]
